# This is a basic workflow to help you get started with Actions

name: upload-ghpages

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Pull docker image
      run: docker pull smellman/tippecanoe:latest

    # Runs a set of commands using the runners shell
    - name: extract xzy and push
      run: |
        docker run --rm -v $(pwd):/working -w /working smellman/tippecanoe:latest tile-join -e zxy tokyo.mbtiles
        rm -fr .git
        rm -fr tokyo.mbtiles
        rm -fr Tokyo.poly
        git init .
        git config user.name $git_name
        git config user.email $git_email
        touch .nojekyll
        git add .
        git commit --quiet -m "Deploy from Github Action"
        git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@$GITHUB_REPOSITORY" master:gh-pages > /dev/null 2>&1
      env:
        git_name: Taro Matsuzawa
        git_email: btm@tech.email.ne.jp  
